# Generated by Django 5.0.4 on 2024-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_tenant_first_name_remove_tenant_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='contact_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
