# Generated by Django 5.0.4 on 2024-10-02 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_user'),
        ('tenants', '0005_alter_tenant_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
