# Generated by Django 5.0.4 on 2024-10-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_room_alter_tenant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_email',
            field=models.EmailField(default='isha', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_first',
            field=models.CharField(default='xyz', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_ph',
            field=models.CharField(default='123456789', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_surname',
            field=models.CharField(default='ex@example.com', max_length=255),
            preserve_default=False,
        ),
    ]
