# Generated by Django 5.0.4 on 2024-11-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_aadhar_number_tenant_is_aadhar_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='room',
        ),
        migrations.AddField(
            model_name='tenant',
            name='bed_allocated',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tenant',
            name='room_representation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
