# Generated by Django 5.0.4 on 2024-11-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_manager_contact_and_more'),
        ('tenants', '0009_remove_tenant_room_tenant_bed_allocated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.room'),
            preserve_default=False,
        ),
    ]
