# Generated by Django 5.0.4 on 2024-11-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='bed_allocated',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='room_representation',
        ),
    ]
