# Generated by Django 5.0.4 on 2024-11-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_remove_tenant_bed_allocated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='bed_allocated',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='room_selected',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
