# Generated by Django 5.0.4 on 2024-11-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_bed_allocated_tenant_room_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='room_selected',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
