# Generated by Django 5.0.4 on 2024-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_alter_tenant_room_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
