# Generated by Django 5.0.4 on 2024-11-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenant_check_in_date_tenant_check_out_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='room_selected',
        ),
    ]
