# Generated by Django 5.0.4 on 2024-11-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_tenant_room_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='bed_allocated',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
