# Generated by Django 5.1.1 on 2024-09-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_address', models.TextField()),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_contact', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('total_beds', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathrooms', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('living_area', models.BooleanField(default=False)),
                ('dining_area', models.BooleanField(default=False)),
                ('workspace', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('security_features', models.BooleanField(default=False)),
                ('community_facilities', models.BooleanField(default=False)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.room')),
            ],
        ),
    ]
