# Generated by Django 5.1.1 on 2024-09-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='type',
        ),
    ]
