# Generated by Django 5.1.1 on 2024-09-28 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_property_address_property_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='property_address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='type',
            new_name='property_type',
        ),
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),

        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_number', 'property')},
        ),
    ]
