# Generated by Django 5.0.4 on 2024-11-04 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='manager_contact',
            field=models.CharField(help_text='Enter the contact number of the property manager.', max_length=100, verbose_name='Manager Contact'),
        ),
        migrations.AlterField(
            model_name='property',
            name='manager_name',
            field=models.CharField(help_text='Enter the name of the property manager.', max_length=100, verbose_name='Manager Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_address',
            field=models.TextField(help_text='Enter the complete address of the property.', verbose_name='Property Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, help_text='Upload an image of the property (optional).', null=True, upload_to='property_images/', verbose_name='Property Image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(help_text='Enter the name of the property.', max_length=255, verbose_name='Property Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(help_text='Specify the type of property (e.g., apartment, house).', max_length=100, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(help_text='Select the user managing this property.', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(help_text='Select the property this room belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(help_text='Enter the room number.', max_length=10, verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_beds',
            field=models.IntegerField(help_text='Enter the total number of beds in this room.', verbose_name='Total Beds'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='bathrooms',
            field=models.BooleanField(default=False, help_text='Is there a bathroom in the room?', verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='community_facilities',
            field=models.BooleanField(default=False, help_text='Are there community facilities available?', verbose_name='Community Facilities'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='dining_area',
            field=models.BooleanField(default=False, help_text='Is there a dining area in the room?', verbose_name='Dining Area'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='kitchen',
            field=models.BooleanField(default=False, help_text='Is there a kitchen in the room?', verbose_name='Kitchen'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='living_area',
            field=models.BooleanField(default=False, help_text='Is there a living area in the room?', verbose_name='Living Area'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='parking',
            field=models.BooleanField(default=False, help_text='Is parking available?', verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='room',
            field=models.OneToOneField(help_text='Select the room for which these amenities apply.', on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='security_features',
            field=models.BooleanField(default=False, help_text='Does the property have security features?', verbose_name='Security Features'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='workspace',
            field=models.BooleanField(default=False, help_text='Is there a workspace in the room?', verbose_name='Workspace'),
        ),
    ]
