# Generated by Django 5.0.4 on 2024-11-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_manager_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(help_text='Enter the room number.', max_length=10, verbose_name='Room Number'),
        ),
    ]
