# Generated by Django 5.0.4 on 2024-11-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(help_text='Enter the room number.', verbose_name='Room Number'),
        ),
    ]
