# Generated by Django 5.0.4 on 2024-11-11 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0007_alter_room_room_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brief description of the expense (e.g., Plumbing Repair, Furniture).', max_length=255, verbose_name='Expense Name')),
                ('document', models.FileField(blank=True, help_text='Upload a document or receipt for this expense.', null=True, upload_to='expense_documents/', verbose_name='Expense Document')),
                ('supervisor', models.CharField(help_text='Name of the person supervising the expense.', max_length=255, verbose_name='Supervisor')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount spent for this expense.', max_digits=10, verbose_name='Amount Spent')),
                ('date_incurred', models.DateField(auto_now_add=True, help_text='The date this expense was incurred.', verbose_name='Date Incurred')),
                ('description', models.TextField(blank=True, help_text='Additional details or notes about this expense.', null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(help_text='The user who logged this expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location', models.ForeignKey(help_text='Room or area where the expense was incurred.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.room', verbose_name='Location')),
                ('property', models.ForeignKey(help_text='Property associated with this expense.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date_incurred'],
            },
        ),
    ]
